apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 8.13.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef: 
    name: quickstart
  podTemplate:
    spec: 
      containers:
        - name: apm-server
          env:
            - name: "ES_PASSWORD"
              valueFrom:
                secretKeyRef: 
                  key: elastic
                  name: quickstart-es-elastic-user
  config:
    monitoring:
      enabled: true
      elasticsearch:
        username: elastic
        password: ${ES_PASSWORD}